### ISSUE TITLE
Corrupt/Missing Address data fields

### ISSUE THREAD

**Issue by mhatreapurva** [Data-Analysis-for-Employee-Atrrition/Employee-Attrition-Analysis#5]
I can see the entries in the address are not validated, many have used abbreviations with the address fields. Also because of the abbreviations I can see some address' are getting marked outside of India. We need a fix for this. I was actually thinking of dropping this field.

Let me know what you think.

**Comment by avantidotpy** [comment]
There are two classes of addresses in the dataset - Permanent and Correspondence. Dropping permanent address makes sense but not correspondence since that data field is relevant for 'Distance from home' field. Let's map this out in terms of kilometres since it will be easy to categorise later.

**Comment by mhatreapurva** [comment]
In that case we need to use Harvensine Formula.

Have a look for some intuition: https://en.wikipedia.org/wiki/Haversine_formula

**Comment by avantidotpy** [comment]
Okay cool.
I have used the formula and categorised it into 4 classes. Have a look

**Comment by mhatreapurva** [comment]
The analysis you did took care of the address, I am closing this issue. Good job :)
